// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  列出全部倒计时项（存储顺序返回，排序展示由前端负责）。 */
	listItems: () => __TAURI_INVOKE<CountdownItem[]>("list_items"),
	addItem: (title: string, targetDate: string, note: string | null) => __TAURI_INVOKE<CountdownItem>("add_item", { title, targetDate, note }),
	updateItem: (id: string, title: string, targetDate: string, note: string | null) => __TAURI_INVOKE<null>("update_item", { id, title, targetDate, note }),
	deleteItem: (id: string) => __TAURI_INVOKE<null>("delete_item", { id }),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	setSettings: (settings: Settings) => __TAURI_INVOKE<Settings>("set_settings", { settings }),
};

/* Types */
export type ColumnWidths = {
	/**  各列宽度（px），可拖拽调整；默认值适配 320px 初始窗口，clamp 范围见 sanitized() */
	name?: number,
	target?: number,
	remaining?: number,
	note?: number,
};

export type CountdownItem = {
	id: string,
	title: string,
	/**  目标日期，`YYYY-MM-DD` */
	target_date: string,
	note: string | null,
	/**  创建时间，RFC3339（仅记录，不参与倒计时显示） */
	created_at: string,
};

export type Settings = {
	/**  临近阈值（天）：剩余天数 ≤ 该值时前端标红；默认 3 */
	red_threshold_days?: number,
	/**  表格四列宽度（px） */
	column_widths?: ColumnWidths,
};

