// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  列出全部倒计时项（存储顺序返回，排序展示由前端负责）。 */
	listItems: () => __TAURI_INVOKE<CountdownItem[]>("list_items"),
	addItem: (title: string, targetDate: string, note: string | null) => __TAURI_INVOKE<CountdownItem>("add_item", { title, targetDate, note }),
	updateItem: (id: string, title: string, targetDate: string, note: string | null) => __TAURI_INVOKE<null>("update_item", { id, title, targetDate, note }),
	deleteItem: (id: string) => __TAURI_INVOKE<null>("delete_item", { id }),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	setSettings: (settings: Settings) => __TAURI_INVOKE<Settings>("set_settings", { settings }),
	/**
	 *  打开设置窗口（前端 ⚙ 按钮调用）。
	 *  必须是 async 命令：WebviewWindowBuilder::build() 在 Windows 上于同步命令中
	 *  会死锁（官方文档明确警告，命令/事件处理器里要改用 async 或独立线程）。
	 */
	openSettings: () => __TAURI_INVOKE<null>("open_settings"),
	/**  导出全部倒计时项（不含设置）。 */
	exportItems: (path: string) => __TAURI_INVOKE<null>("export_items", { path }),
	/**  导入倒计时（替换现有全部倒计时项，设置不动）。 */
	importItems: (path: string) => __TAURI_INVOKE<ImportItemsResult>("import_items", { path }),
	/**  导出设置（不含倒计时项）。 */
	exportSettings: (path: string) => __TAURI_INVOKE<null>("export_settings", { path }),
	/**  导入设置（替换现有设置，倒计时项不动）。 */
	importSettings: (path: string) => __TAURI_INVOKE<null>("import_settings", { path }),
};

/* Types */
export type ColumnWidths = {
	/**  各列宽度（px），可拖拽调整；默认值适配 320px 初始窗口，clamp 范围见 sanitized() */
	name?: number,
	target?: number,
	/**  倒计时列 */
	countdown?: number,
	note?: number,
};

export type CountdownItem = {
	id: string,
	title: string,
	/**  目标日期，`YYYY-MM-DD` */
	target_date: string,
	note: string | null,
	/**  创建时间，RFC3339（仅记录，不参与倒计时显示） */
	created_at: string,
};

export type ImportItemsResult = {
	/**  导入的倒计时条数 */
	items: number,
};

export type Settings = {
	/**  紧急度分级：按阈值降序存储；过期固定红色，不在此列 */
	levels?: UrgencyLevel[],
	/**  表格四列宽度（px） */
	column_widths?: ColumnWidths,
};

/**  紧急度分级：剩余天数 ≤ threshold_days 时该行采用 color 显示（含当天 days = 0）。 */
export type UrgencyLevel = {
	threshold_days: number,
	/**  行文字颜色，`#RRGGBB` */
	color: string,
};

