// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  列出全部倒计时项（存储顺序返回，排序展示由前端负责）。 */
	listItems: () => __TAURI_INVOKE<CountdownItem[]>("list_items"),
	addItem: (title: string, targetDate: string, note: string | null) => __TAURI_INVOKE<CountdownItem>("add_item", { title, targetDate, note }),
	updateItem: (id: string, title: string, targetDate: string, note: string | null) => __TAURI_INVOKE<null>("update_item", { id, title, targetDate, note }),
	deleteItem: (id: string) => __TAURI_INVOKE<null>("delete_item", { id }),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	setSettings: (settings: Settings) => __TAURI_INVOKE<Settings>("set_settings", { settings }),
	/**
	 *  打开设置窗口（前端 ⚙ 按钮调用）。
	 *  必须是 async 命令：WebviewWindowBuilder::build() 在 Windows 上于同步命令中
	 *  会死锁（官方文档明确警告，命令/事件处理器里要改用 async 或独立线程）。
	 */
	openSettings: () => __TAURI_INVOKE<null>("open_settings"),
	/**
	 *  字体中文名映射（数据目录 `font-family-map.toml`，缺失时写入默认模板）。
	 *  仅用于设置页下拉的显示文案，失败回落内置默认映射、不报错。
	 */
	getFontFamilyMap: () => __TAURI_INVOKE<{ [key in string]: string }>("get_font_family_map"),
	/**  导出全部倒计时项（不含设置）。 */
	exportItems: (path: string) => __TAURI_INVOKE<null>("export_items", { path }),
	/**  导入倒计时（替换现有全部倒计时项，设置不动）。 */
	importItems: (path: string) => __TAURI_INVOKE<ImportItemsResult>("import_items", { path }),
	/**  导出设置（不含倒计时项）。 */
	exportSettings: (path: string) => __TAURI_INVOKE<null>("export_settings", { path }),
	/**  导入设置（替换现有设置，倒计时项不动）。 */
	importSettings: (path: string) => __TAURI_INVOKE<null>("import_settings", { path }),
	/**
	 *  打开日期选择弹窗（前端点击日期框调用）。必须是 async 命令
	 *  （WebviewWindowBuilder::build 在同步命令里于 Windows 上死锁，官方文档警告）。
	 */
	openDatePicker: (x: number | null, y: number | null, date: string | null) => __TAURI_INVOKE<null>("open_date_picker", { x, y, date }),
	/**  弹窗挂载时读取初始选中值（ISO 字符串，无则返回 None）。 */
	getDatePickerPayload: () => __TAURI_INVOKE<string | null>("get_date_picker_payload"),
	/**  选中日期后由弹窗调用：隐藏自身（窗口保留供复用）。 */
	closeDatePicker: () => __TAURI_INVOKE<null>("close_date_picker"),
	/**  前端上报日志：经全局级别过滤，被过滤的日志不落盘（前端有本地缓存预判）。 */
	logMsg: (level: string, message: string) => __TAURI_INVOKE<void>("log_msg", { level, message }),
	/**  查询当前全局最低日志级别（小写字符串，供前端启动时同步缓存）。 */
	getLogLevel: () => __TAURI_INVOKE<string>("get_log_level"),
	/**  运行时热切全局最低日志级别，并 emit 事件让前端刷新缓存。 */
	setLogLevel: (level: string) => __TAURI_INVOKE<null>("set_log_level", { level }),
};

/** Events */
export const events = {
	logLevelChanged: makeEvent<LogLevelChanged>("log-level-changed"),
};

/* Types */
export type ColumnWidths = {
	/**  各列宽度（px），可拖拽调整；默认值适配 320px 初始窗口，clamp 范围见 sanitized() */
	name?: number,
	target?: number,
	/**  倒计时列 */
	countdown?: number,
	note?: number,
};

export type CountdownItem = {
	id: string,
	title: string,
	/**  目标日期，`YYYY-MM-DD` */
	target_date: string,
	note: string | null,
	/**  创建时间，RFC3339（仅记录，不参与倒计时显示） */
	created_at: string,
};

export type ImportItemsResult = {
	/**  导入的倒计时条数 */
	items: number,
};

/**  日志级别变更事件（payload 为新级别小写字符串），前端监听后刷新本地缓存。 */
export type LogLevelChanged = string;

export type Settings = {
	/**  紧急度分级：按阈值降序存储；过期固定红色，不在此列 */
	levels?: UrgencyLevel[],
	/**  表格四列宽度（px） */
	column_widths?: ColumnWidths,
	/**  主窗口置顶（标题栏图钉切换）；旧数据缺字段按默认置顶处理 */
	always_on_top?: boolean,
	/**
	 *  全局热键 accelerator（如 `Ctrl+Alt+C`）唤起主窗口；None = 关闭热键。
	 *  字段缺失（旧数据）回落默认键，显式 null 表示用户关闭 —— serde 只在缺失时用 default。
	 */
	hotkey?: string | null,
	/**  主窗口背景透明度（%），10–100；旧数据缺字段按不透明处理 */
	background_opacity?: number,
	/**  主窗口背景色 `#RRGGBB`；非法值回落默认色 */
	background_color?: string,
	/**
	 *  全局字体家族：完整 CSS font-family 值（如 `"Microsoft YaHei", sans-serif`）；
	 *  空串 = 跟随系统默认栈（旧数据缺字段即落这里，行为不变）
	 */
	font_family?: string,
};

/**  紧急度分级：剩余天数 ≤ threshold_days 时该行采用 color 显示（含当天 days = 0）。 */
export type UrgencyLevel = {
	threshold_days: number,
	/**  行文字颜色，`#RRGGBB` */
	color: string,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

